name: Test Composite action
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: composite action
        uses: ./.github/actions/demo-action